[package]
name = "Trust16"
version = "0.0.1"
authors = ["lay (Aladeen): aladeen@codeandledger.com"]

[addresses]
trust_16 = "0xfeb7aabfa77c176a286b10fa0d0ed118fe309e8d900464a66630238eccd342f9"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
