[package]
name = "Trust16"
version = "0.0.1"
authors = ["lay (Aladeen): aladeen@codeandledger.com"]

[addresses]
trust_16 = "0x7cc93308a827ac3cf3595718295a7e18d8e880e63728b2f52822f4a76ad1233d"
session_manager = "0x9a01c4338e07af8b540990de6d4fb7546a2034166e56befd37da35a8c5fcc655"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
