[package]
name = "TrustCoin"
version = "0.0.1"
authors = ["lay (Aladeen): aladeen@codeandledger.com"]

[addresses]
trust_coin = "0xce3824597867081e7e16b21f4d364f90b1abae40b92e23dd915e5330719c2e98"
dev = "0x2cdf1f17ef5a45e959140abc428ba14aa6d19a1923b2f440a699c04f1930da29"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
